<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions 
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
        	http://schemas.xmlsoap.org/wsdl/ http://schemas.xmlsoap.org/wsdl/
        	http://www.w3.org/2001/XMLSchema https://www.w3.org/2001/XMLSchema.xsd
        "
           
        name="______"
        xmlns:tns="________"
        targetNamespace="________"         
>

</wsdl:definitions>